// app/login/page.tsx
"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, FormEvent } from "react";

export default function LoginPage() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError("");
    setLoading(true);

    try {
      const res = await fetch("/api/auth/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, password }),
      });

      let data;
      try { data = await res.json(); } catch { data = {}; }

      if (!res.ok) {
        setError(data.error || "Login failed");
        return;
      }

      router.push("/dashboard");
    } catch {
      setError("Connection error. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="flex min-h-screen font-sans">
      {/* Left panel */}
      <div className="relative hidden w-1/2 flex-col justify-between overflow-hidden bg-[#075E54] p-12 lg:flex">
        <div className="relative z-10">
          <Link href="/" className="flex items-center gap-2 text-lg font-bold text-white/90">
            <svg className="h-6 w-6 text-[#25D366]" viewBox="0 0 24 24" fill="currentColor">
              <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
            </svg>
            WAGateway
          </Link>
        </div>

        <div className="relative z-10 space-y-6">
          <blockquote className="text-2xl font-light leading-relaxed text-white/90">
            &ldquo;We cut our customer response time by 80% and doubled engagement within the first month.&rdquo;
          </blockquote>
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#25D366]/30 text-sm font-semibold text-white">
              SR
            </div>
            <div>
              <p className="text-sm font-medium text-white">Sarah R.</p>
              <p className="text-xs text-white/60">Product Manager, TechCorp</p>
            </div>
          </div>
        </div>

        <div className="pointer-events-none absolute inset-0 select-none">
          <div className="absolute -right-10 -top-10 h-64 w-64 rounded-full border border-white/5" />
          <div className="absolute -right-20 -top-20 h-80 w-80 rounded-full border border-white/5" />
          <div className="absolute -bottom-10 -left-10 h-48 w-48 rounded-full border border-white/5" />
          <div className="absolute bottom-20 left-12 h-3 w-3 rounded-full bg-[#25D366]/40" />
          <div className="absolute right-20 top-1/3 h-2 w-2 rounded-full bg-[#DCF8C6]/30" />
          <div className="absolute bottom-1/3 left-1/3 h-1.5 w-1.5 rounded-full bg-white/20" />
          <div className="absolute left-1/2 top-1/4 h-3 w-20 rounded-full bg-white/5" />
          <div className="absolute right-12 top-1/2 h-2 w-32 rounded-full bg-white/5" />
          <div className="absolute left-8 bottom-1/4 h-2 w-24 rounded-full bg-white/5" />
        </div>
      </div>

      {/* Right panel */}
      <div className="flex w-full items-center justify-center bg-white px-6 lg:w-1/2">
        <div className="w-full max-w-sm">
          <div className="mb-10 lg:hidden">
            <Link href="/" className="flex items-center gap-2 text-lg font-bold text-[#075E54]">
              <svg className="h-6 w-6 text-[#25D366]" viewBox="0 0 24 24" fill="currentColor">
                <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
              </svg>
              WAGateway
            </Link>
          </div>

          <div className="mb-8">
            <h1 className="text-2xl font-semibold tracking-tight text-[#075E54]">
              Welcome back
            </h1>
            <p className="mt-2 text-sm leading-relaxed text-zinc-500">
              Enter your credentials to access your account.
            </p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-5">
            {error && (
              <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-600">
                {error}
              </div>
            )}

            <div>
              <label htmlFor="email" className="block text-sm font-medium text-zinc-700">
                Email
              </label>
              <input
                id="email"
                type="email"
                autoComplete="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="mt-1.5 block w-full rounded-xl border border-zinc-200 bg-zinc-50/50 px-4 py-3 text-sm text-zinc-900 placeholder:text-zinc-400 transition-colors focus:border-[#25D366] focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#25D366]/15"
                placeholder="you@example.com"
              />
            </div>

            <div>
              <div className="flex items-center justify-between">
                <label htmlFor="password" className="block text-sm font-medium text-zinc-700">
                  Password
                </label>
                <a href="#" className="text-xs font-medium text-[#075E54] transition-colors hover:text-[#25D366]">
                  Forgot?
                </a>
              </div>
              <input
                id="password"
                type="password"
                autoComplete="current-password"
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="mt-1.5 block w-full rounded-xl border border-zinc-200 bg-zinc-50/50 px-4 py-3 text-sm text-zinc-900 placeholder:text-zinc-400 transition-colors focus:border-[#25D366] focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#25D366]/15"
                placeholder="Enter your password"
              />
            </div>

            <label className="flex items-center gap-2.5 text-sm text-zinc-500">
              <input
                type="checkbox"
                className="h-4 w-4 rounded border-zinc-300 text-[#25D366] focus:ring-[#25D366]/30"
              />
              Keep me signed in
            </label>

            <button
              type="submit"
              disabled={loading}
              className="flex h-11 w-full items-center justify-center rounded-xl bg-[#25D366] px-5 text-sm font-semibold text-white shadow-sm transition-all hover:bg-[#1DAF5A] hover:shadow-md focus:outline-none focus:ring-2 focus:ring-[#25D366]/30 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {loading ? "Signing in..." : "Sign in"}
            </button>

            <p className="text-center text-sm text-zinc-400">
              Don&apos;t have an account?{" "}
              <Link href="/register" className="font-medium text-[#075E54] transition-colors hover:text-[#25D366]">
                Create one
              </Link>
            </p>
          </form>
        </div>
      </div>
    </div>
  );
}

// pages/login.vue
<script setup lang="ts">

const colorMode = useColorMode()
const isDark = computed(() => colorMode.value === 'dark')
const showThemeDropdown = ref(false)

definePageMeta({ layout: false })

const authStore = useAuthStore()
const router = useRouter()

const email = ref('')
const password = ref('')
const loading = ref(false)
const error = ref('')

onMounted(() => {
  authStore.init()
  if (authStore.isAuthenticated) {
    router.push('/dashboard')
  }
})

const themeOptions: Array<{ value: 'light' | 'dark' | 'system'; icon: string; bg: string }> = [
  { value: 'light', icon: 'fa-sun', bg: isDark ? '#1b2838' : '#fff7ed' },
  { value: 'dark', icon: 'fa-moon', bg: isDark ? '#0d1b2a' : '#f1f5f9' },
  { value: 'system', icon: 'fa-desktop', bg: isDark ? '#1b2838' : '#f8fafc' },
]

const currentIcon = computed(() => {
  const pref = colorMode.preference as string
  const opt = themeOptions.find(o => o.value === pref)
  return opt?.icon || 'fa-desktop'
})

async function handleLogin() {
  loading.value = true
  error.value = ''

  try {
    const data = await $fetch('/api/auth/login', {
      method: 'POST',
      body: { email: email.value, password: password.value },
    })
    const result = data as any
    if (result.success) {
      authStore.setAuth(result.token, result.user)
      router.push('/dashboard')
    }
    else {
      error.value = result.error || 'Login gagal'
    }
  }
  catch (e: any) {
    error.value = e?.data?.message || e?.message || 'Login gagal'
  }
  finally {
    loading.value = false
  }
}

function setTheme(value: 'light' | 'dark' | 'system') {
  colorMode.preference = value
  showThemeDropdown.value = false
}
</script>

<template>
  <div class="min-h-screen bg-[#0b141a] flex items-center justify-center px-4">
    <!-- Theme Dropdown -->
    <div class="fixed top-4 right-4 z-10">
      <button
        @click="showThemeDropdown = !showThemeDropdown"
        class="w-10 h-10 rounded-xl bg-[#111b21] border border-[#222e35] text-slate-400 hover:text-white flex items-center justify-center transition"
      >
        <i :class="['fas', currentIcon, 'text-sm']"></i>
      </button>
      <div v-if="showThemeDropdown" :class="[
        'absolute right-0 top-12 w-36 rounded-xl border shadow-lg overflow-hidden z-20',
        isDark ? 'bg-[#1b2838] border-[#444c56]' : 'bg-white border-slate-200',
      ]">
        <button
          v-for="opt in themeOptions"
          :key="opt.value"
          @click="setTheme(opt.value)"
          :class="[
            'w-full text-left px-4 py-2.5 text-sm flex items-center space-x-3 transition',
            colorMode.preference === opt.value
              ? (isDark ? 'bg-[#202c33] text-white' : 'bg-emerald-50 text-emerald-700')
              : (isDark ? 'text-slate-400 hover:bg-[#202c33] hover:text-white' : 'text-slate-600 hover:bg-slate-50'),
          ]"
        >
          <i :class="['fas', opt.icon, 'w-4 text-center']"></i>
          <span>{{ opt.value.charAt(0).toUpperCase() + opt.value.slice(1) }}</span>
          <i v-if="colorMode.preference === opt.value" class="fas fa-check ml-auto text-emerald-500"></i>
        </button>
      </div>
    </div>

    <div class="w-full max-w-sm">
      <div class="text-center mb-8">
        <i class="fab fa-whatsapp text-emerald-500 text-5xl mb-4"></i>
        <h1 class="text-2xl font-bold text-white">WA<span class="text-emerald-500">Blaster</span></h1>
        <p class="text-slate-400 text-sm mt-1">WhatsApp Gateway Dashboard</p>
      </div>

      <div class="bg-[#111b21] border border-[#222e35] rounded-2xl p-6">
        <form @submit.prevent="handleLogin" class="space-y-4">
          <div>
            <label class="block text-sm font-medium text-slate-400 mb-1">Email</label>
            <input
              v-model="email"
              type="email"
              placeholder="admin@example.com"
              required
              class="w-full bg-[#202c33] border border-[#222e35] rounded-xl px-4 py-3 text-white placeholder-slate-500 focus:outline-none focus:border-emerald-500 transition-colors"
            />
          </div>
          <div>
            <label class="block text-sm font-medium text-slate-400 mb-1">Password</label>
            <input
              v-model="password"
              type="password"
              placeholder="Masukkan password"
              required
              class="w-full bg-[#202c33] border border-[#222e35] rounded-xl px-4 py-3 text-white placeholder-slate-500 focus:outline-none focus:border-emerald-500 transition-colors"
            />
          </div>
          <p v-if="error" class="text-rose-400 text-sm">{{ error }}</p>
          <button
            type="submit"
            :disabled="loading"
            class="w-full bg-emerald-500 hover:bg-emerald-600 text-white font-medium py-3 rounded-xl transition disabled:opacity-50"
          >
            {{ loading ? 'Memproses...' : 'Masuk' }}
          </button>
        </form>
        <p class="text-center text-sm text-slate-400 mt-4">
          Belum punya akun?
          <NuxtLink to="/register" class="text-emerald-400 hover:text-emerald-300 font-medium">Daftar</NuxtLink>
        </p>
      </div>
    </div>
  </div>
</template>
